// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfkqNp2kigjIXOTklsCW3L0Qf0XHEdxpE',
    appId: '1:506724439826:web:89f39ffa5358906f6c45cb',
    messagingSenderId: '506724439826',
    projectId: 'hotelapin',
    authDomain: 'hotelapin.firebaseapp.com',
    storageBucket: 'hotelapin.appspot.com',
    measurementId: 'G-NN05L1H9CZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk9g7Oixpsk_z-ryge9VlL6qEUz7wEqUY',
    appId: '1:506724439826:android:4181c6f322c709a66c45cb',
    messagingSenderId: '506724439826',
    projectId: 'hotelapin',
    storageBucket: 'hotelapin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBouawpQxetVquGD9e7mJojDHl9GflVUgs',
    appId: '1:506724439826:ios:221b87f1bed48c3c6c45cb',
    messagingSenderId: '506724439826',
    projectId: 'hotelapin',
    storageBucket: 'hotelapin.appspot.com',
    iosBundleId: 'com.example.hotelApin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBouawpQxetVquGD9e7mJojDHl9GflVUgs',
    appId: '1:506724439826:ios:221b87f1bed48c3c6c45cb',
    messagingSenderId: '506724439826',
    projectId: 'hotelapin',
    storageBucket: 'hotelapin.appspot.com',
    iosBundleId: 'com.example.hotelApin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfkqNp2kigjIXOTklsCW3L0Qf0XHEdxpE',
    appId: '1:506724439826:web:a16868b8bc8403ae6c45cb',
    messagingSenderId: '506724439826',
    projectId: 'hotelapin',
    authDomain: 'hotelapin.firebaseapp.com',
    storageBucket: 'hotelapin.appspot.com',
    measurementId: 'G-6VEJJM49Y6',
  );
}
